import Vue from 'vue'
import { Lazyload, Loading, Field, Button, Form, NavBar, Tabbar, TabbarItem, Icon, Tab, Tabs, Cell, List, PullRefresh, ActionSheet, Popup, Grid, GridItem, Row, Badge, Col, Search, Divider, Image as VanImage, Tag, CellGroup, Dialog, DatetimePicker } from 'vant'

Vue.use(Lazyload)
Vue.use(Loading)
Vue.use(DatetimePicker)
Vue.use(Dialog)
Vue.use(CellGroup)
Vue.use(Tag)
Vue.use(VanImage)
Vue.use(Divider)
Vue.use(Search)
Vue.use(Row)
Vue.use(Badge)
Vue.use(Col)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(Popup)
Vue.use(ActionSheet)
Vue.use(PullRefresh)
Vue.use(List)
Vue.use(Cell)
Vue.use(Tab)
Vue.use(Tabs)
Vue.use(Icon)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(NavBar)
Vue.use(Form)
Vue.use(Field)
Vue.use(Button)
